version: '3'
services:
    web:
        build: .
        restart: always
        ports:
            - "5050:5000"
        volumes:
            - .:/web
            - ./instance/paper_select.sqlite:/web/instance/paper_select.sqlite

